# Generated by Django 5.0.6 on 2024-09-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_neme',
            new_name='user_name',
        ),
    ]
